use_nerdfont=true

[keybindings]
"Ctrl+d" = "move down 5"
"Ctrl+u" = "move up 5"
"G" = "move bottom"
"gg" = "move top"

# # Spotify
# [theme]
# background = "black"
# primary = "light white"
# secondary = "light black"
# title = "green"
# playing = "green"
# playing_selected = "light green"
# playing_bg = "black"
# highlight = "light white"
# highlight_bg = "#484848"
# error = "light white"
# error_bg = "red"
# statusbar = "black"
# statusbar_progress = "green"
# statusbar_bg = "green"
# cmdline = "light white"
# cmdline_bg = "black"

# # Base16_sol_dark, modified closer to spotify colors by BachoSeven, originally https://github.com/gidsi/base16-ncspot
# [theme]
# background = "#002b36"
# primary = "#eee8d5"
# secondary = "#2aa198"
# title = "#859900"
# playing = "#268bd2"
# playing_selected = "light green"
# playing_bg = "#002b36"
# highlight = "#93a1a1"
# highlight_bg = "#484848"
# error = "#93a1a1"
# error_bg = "#fdf6e3"
# statusbar = "#002b36"
# statusbar_progress = "#dc322f"
# statusbar_bg = "#859900"
# cmdline = "#93a1a1"
# cmdline_bg = "#002b36"

# Gruvbox dark [ based on base16 by Dawid Kurek (dawikur@gmail.com) ]
[theme]
background = "#282828"
primary = "#1d2021"
secondary = "#458588"
title = "#fbf1c7"
playing = "#d79921"
playing_bg = "#282828"
playing_selected = "#98971a"
highlight = "#d5c4a1"
highlight_bg = "#282828"
error = "#d5c4a1"
error_bg = "#fbf1c7"
statusbar = "#555555"
statusbar_progress = "#b16286"
statusbar_bg = "#98971a"
cmdline = "#d5c4a1"
cmdline_bg = "#282828"
